### ISSUE TITLE
Serialize/Deserialize Poseidon Constants

### ISSUE THREAD

**Issue by arthurgreef** [filecoin-project/neptune#146]
Hi - [Nova's](https://github.com/microsoft/Nova/blob/0154358469e9de1745f41dd1d1bd71212f58fbaf/src/poseidon.rs#:~:text=%23%5Bderive(Clone)%5D,%7D) public parameters reference [Neptune's Poseidon Hash Constants](https://github.com/filecoin-project/neptune/blob/master/src/poseidon.rs#:~:text=%7D-,%23%5Bderive(Debug%2C%20Clone%2C%20PartialEq)%5D,pub%20struct%20PoseidonConstants%3CF%2C%20A%3E,-where). We would like to serialize/deserialize Nova's public parameters using serde. What do you'll think about adding serde derive as an optional feature so that we can serialize/deserialize? It gets a bit tricky when it comes to serialize/deserialize of UInt from typenum so I was just wandering if anyone had any thoughts on that. Thanks.

**Comment by porcuquine** [comment]
I agree this will be useful, though I note a stopgap would be to regenerate the parameters on deserialization — which may be tolerable for use cases where the public parameters are cached in memory (which probably makes sense).

I haven't given thought to the typenum issue, but will something like this work? https://www.reddit.com/r/rust/comments/5z3t5j/hey_rustaceans_got_an_easy_question_ask_here/dewmhjl/?context=3

If you have thoughts, a PR would be welcome.

cc: @vmx, @johnchandlerburnham, @dignifiedquire — all of whom may have insight and/or bandwidth.

---

Also note: in the future, it may be that only a single arity is required in the public parameters, in which case some of this complexity might disappear. (The idea is to support the Nova random oracle via sponge in Neptune, so there is no dependence on either the number of elements to be absorbed or on the arity of the the inner function F.)

Given that, *if* the typenum issue turns out to be problematic, it might be easier to wait — although I realize this wouldn't address the general problem of serialization/deserialization for Neptune.

**Comment by arthurgreef** [comment]
Thanks. I'll wait for you'll to remove the dependency. The typenum package provides an optional serde feature but only for generic-array and not arraylength. Is there an issue I can subscribe to track the Nova sponge support? Also, it seems problematic to support serde as an optional feature in Neptune because of the use of bounds constraints in structs and implementations. It seems as though to use serde derive you need to have one copy of a struct or impl for when the serde feature is enabled and when it is not. Would you want serde to be an optional feature? Thanks.
